// <auto-generated />
using System;
using MerchForge.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerchForge.api.Migrations
{
    [DbContext(typeof(MerchForgeDbContext))]
    [Migration("20260821155658_MakeProductDescriptionNullable")]
    partial class MakeProductDescriptionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MerchForge.api.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BusinessDomainId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("en-US");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MetadataShape")
                        .HasColumnType("json")
                        .HasColumnName("meta_data_shape");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("WebsiteTemplateChosenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("WebsiteTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("WebsiteTemplateId");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.BusinessDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("business_domains", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Fashion",
                            Slug = "fashion",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Restaurant",
                            Slug = "restaurant",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Electronics",
                            Slug = "electronics",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.BusinessUser", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BusinessUserRoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BusinessId", "UserId");

                    b.HasIndex("BusinessUserRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("business_users", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.BusinessUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BusinessUserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Role = "Owner"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessDomainId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessDomainId", "BusinessId", "Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Shoes",
                            Slug = "shoes",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000002"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Shirts",
                            Slug = "shirts",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-4000-8000-000000000003"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Accessories",
                            Slug = "accessories",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Pizza",
                            Slug = "pizza",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-4000-8000-000000000002"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Burgers",
                            Slug = "burgers",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-4000-8000-000000000003"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Drinks",
                            Slug = "drinks",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Phones",
                            Slug = "phones",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3000000-0000-4000-8000-000000000002"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Laptops",
                            Slug = "laptops",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3000000-0000-4000-8000-000000000003"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Accessories",
                            Slug = "accessories",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("BusinessRole")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("EmailDeliveryError")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EmailDeliveryFailedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SystemRole")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MerchForge.api.Models.PlanFeature", b =>
                {
                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Limit")
                        .HasColumnType("int");

                    b.HasKey("SubscriptionPlanId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("plan_features", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("SaleEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasDefaultValueSql("(JSON_ARRAY())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("BusinessId", "CategoryId");

                    b.HasIndex("BusinessId", "Sku")
                        .IsUnique();

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_CompareAtPrice_GreaterThanPrice", "`CompareAtPrice` IS NULL OR `CompareAtPrice` > `Price`");

                            t.HasCheckConstraint("CK_products_StockQuantity_NonNegative", "`StockQuantity` IS NULL OR `StockQuantity` >= 0");
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.ProductAttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AllowedValues")
                        .HasColumnType("json");

                    b.Property<Guid>("BusinessDomainId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId", "Key")
                        .IsUnique();

                    b.ToTable("product_attribute_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsRequired = true,
                            Key = "colors",
                            Label = "Colors",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "ColorList"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000002"),
                            AllowedValues = "[\"XS\",\"S\",\"M\",\"L\",\"XL\",\"2XL\"]",
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsRequired = true,
                            Key = "sizes",
                            Label = "Sizes",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "TextList"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000003"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsRequired = false,
                            Key = "material",
                            Label = "Material",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000004"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsRequired = false,
                            Key = "fit",
                            Label = "Fit",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000005"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            IsRequired = false,
                            Key = "pattern",
                            Label = "Pattern",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000006"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            IsRequired = false,
                            Key = "gender",
                            Label = "Gender",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000007"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            IsRequired = false,
                            Key = "season",
                            Label = "Season",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000008"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsActive = true,
                            IsRequired = false,
                            Key = "careInstructions",
                            Label = "Care instructions",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-000000000009"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsActive = true,
                            IsRequired = false,
                            Key = "countryOfOrigin",
                            Label = "Country of origin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-00000000000a"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = false,
                            Key = "handmade",
                            Label = "Handmade",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Boolean"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-4000-8000-00000000000b"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            IsActive = true,
                            IsRequired = false,
                            Key = "brand",
                            Label = "Brand",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsRequired = false,
                            Key = "ingredients",
                            Label = "Ingredients",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "TextList"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000002"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsRequired = false,
                            Key = "allergens",
                            Label = "Allergens",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "TextList"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000003"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsRequired = false,
                            Key = "spicy",
                            Label = "Spicy",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Boolean"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000004"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsRequired = false,
                            Key = "vegetarian",
                            Label = "Vegetarian",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Boolean"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000005"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            IsRequired = false,
                            Key = "vegan",
                            Label = "Vegan",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Boolean"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000006"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            IsRequired = false,
                            Key = "glutenFree",
                            Label = "Gluten free",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Boolean"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000007"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            IsRequired = false,
                            Key = "calories",
                            Label = "Calories",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Number"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000008"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsActive = true,
                            IsRequired = false,
                            Key = "portionSize",
                            Label = "Portion size",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-000000000009"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsActive = true,
                            IsRequired = false,
                            Key = "preparationMinutes",
                            Label = "Preparation time (minutes)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Number"
                        },
                        new
                        {
                            Id = new Guid("a2000000-0000-4000-8000-00000000000a"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = false,
                            Key = "servingTemperature",
                            Label = "Serving temperature",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsRequired = false,
                            Key = "brand",
                            Label = "Brand",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000002"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsRequired = false,
                            Key = "model",
                            Label = "Model",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000003"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsRequired = false,
                            Key = "storage",
                            Label = "Storage",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000004"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsRequired = false,
                            Key = "ram",
                            Label = "RAM",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000005"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            IsRequired = false,
                            Key = "screenSize",
                            Label = "Screen size",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000006"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            IsRequired = false,
                            Key = "batteryCapacity",
                            Label = "Battery capacity",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000007"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            IsRequired = false,
                            Key = "colors",
                            Label = "Colors",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "ColorList"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000008"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsActive = true,
                            IsRequired = false,
                            Key = "connectivity",
                            Label = "Connectivity",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "TextList"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-000000000009"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsActive = true,
                            IsRequired = false,
                            Key = "operatingSystem",
                            Label = "Operating system",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Text"
                        },
                        new
                        {
                            Id = new Guid("a3000000-0000-4000-8000-00000000000a"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            IsActive = true,
                            IsRequired = false,
                            Key = "warrantyMonths",
                            Label = "Warranty (months)",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValueType = "Number"
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.ProductDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Draft")
                        .HasColumnType("json");

                    b.Property<string>("ImageModificationPrompt")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Messages")
                        .HasColumnType("json");

                    b.Property<string>("OriginalImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProcessedImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BusinessId", "Status");

                    b.HasIndex("BusinessId", "Provider", "ConversationId");

                    b.ToTable("product_drafts", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MainImageProductId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("char(36)")
                        .HasComputedColumnSql("(CASE WHEN `IsMain` = 1 THEN `ProductId` ELSE NULL END)", true);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainImageProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_product_images_OneMainPerProduct");

                    b.HasIndex("ProductId", "DisplayOrder");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ExternalSubscriptionId")
                        .IsUnique()
                        .HasFilter("external_subscription_id IS NOT NULL");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SystemRoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserRoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserRoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MerchForge.api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Role = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Role = "User"
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.WebsiteTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessDomainId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideoPreviewUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDomainId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("website_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000001"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Vineta Fashion",
                            Name = "fashion-template-01",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VideoPreviewUrl = "/videos/templates/coming-soon.mp4"
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-4000-8000-000000000002"),
                            BusinessDomainId = new Guid("d1000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Vineta Electronics",
                            Name = "electronic-template-01",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VideoPreviewUrl = "/videos/templates/coming-soon.mp4"
                        });
                });

            modelBuilder.Entity("MerchForge.api.Models.Business", b =>
                {
                    b.HasOne("MerchForge.api.Models.BusinessDomain", "BusinessDomain")
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerchForge.api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.WebsiteTemplate", "WebsiteTemplate")
                        .WithMany("Businesses")
                        .HasForeignKey("WebsiteTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusinessDomain");

                    b.Navigation("Owner");

                    b.Navigation("WebsiteTemplate");
                });

            modelBuilder.Entity("MerchForge.api.Models.BusinessUser", b =>
                {
                    b.HasOne("MerchForge.api.Models.Business", "Business")
                        .WithMany("Members")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.BusinessUserRole", null)
                        .WithMany("BusinessMemberships")
                        .HasForeignKey("BusinessUserRoleId");

                    b.HasOne("MerchForge.api.Models.User", "User")
                        .WithMany("BusinessMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MerchForge.api.Models.Category", b =>
                {
                    b.HasOne("MerchForge.api.Models.BusinessDomain", "BusinessDomain")
                        .WithMany("Categories")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.Business", "Business")
                        .WithMany("CustomCategories")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Business");

                    b.Navigation("BusinessDomain");
                });

            modelBuilder.Entity("MerchForge.api.Models.Invitation", b =>
                {
                    b.HasOne("MerchForge.api.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerchForge.api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MerchForge.api.Models.PlanFeature", b =>
                {
                    b.HasOne("MerchForge.api.Models.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("MerchForge.api.Models.Product", b =>
                {
                    b.HasOne("MerchForge.api.Models.Business", "Business")
                        .WithMany("Products")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MerchForge.api.Models.ProductAttributeDefinition", b =>
                {
                    b.HasOne("MerchForge.api.Models.BusinessDomain", "BusinessDomain")
                        .WithMany("ProductAttributeDefinitions")
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessDomain");
                });

            modelBuilder.Entity("MerchForge.api.Models.ProductDraft", b =>
                {
                    b.HasOne("MerchForge.api.Models.Business", "Business")
                        .WithMany("ProductDrafts")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Business");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MerchForge.api.Models.ProductImage", b =>
                {
                    b.HasOne("MerchForge.api.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MerchForge.api.Models.RefreshToken", b =>
                {
                    b.HasOne("MerchForge.api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MerchForge.api.Models.Subscription", b =>
                {
                    b.HasOne("MerchForge.api.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerchForge.api.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("MerchForge.api.Models.User", b =>
                {
                    b.HasOne("MerchForge.api.Models.UserRole", null)
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId");
                });

            modelBuilder.Entity("MerchForge.api.Models.WebsiteTemplate", b =>
                {
                    b.HasOne("MerchForge.api.Models.BusinessDomain", "BusinessDomain")
                        .WithMany()
                        .HasForeignKey("BusinessDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessDomain");
                });

            modelBuilder.Entity("MerchForge.api.Models.Business", b =>
                {
                    b.Navigation("CustomCategories");

                    b.Navigation("Members");

                    b.Navigation("ProductDrafts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MerchForge.api.Models.BusinessDomain", b =>
                {
                    b.Navigation("Businesses");

                    b.Navigation("Categories");

                    b.Navigation("ProductAttributeDefinitions");
                });

            modelBuilder.Entity("MerchForge.api.Models.BusinessUserRole", b =>
                {
                    b.Navigation("BusinessMemberships");
                });

            modelBuilder.Entity("MerchForge.api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MerchForge.api.Models.Feature", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("MerchForge.api.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MerchForge.api.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("PlanFeatures");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MerchForge.api.Models.User", b =>
                {
                    b.Navigation("BusinessMemberships");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MerchForge.api.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MerchForge.api.Models.WebsiteTemplate", b =>
                {
                    b.Navigation("Businesses");
                });
#pragma warning restore 612, 618
        }
    }
}
